In [76]:
import pandas as pd
import numpy

In [77]:
dirpath = 'C:/Users/mvgarcia/Downloads/ComiteEmpresa/cb/2024/'
raw_data = pd.read_csv(dirpath + 'Preprocessed.csv')

In [78]:
raw_data.head()

              Id       Fecha  Retribucion  Area Grupo  Nivel
0  07.10.2024000  07.10.2024      18500.0     3     E      1
1  14.02.2024001  14.02.2024      18500.0     3     E      1
2  16.09.2024002  16.09.2024      23000.0     4     D      1
3  24.06.2024003  24.06.2024      18000.0     3     E      2
4  04.11.2024004  04.11.2024      22000.0     3     D      1

In [80]:
raw_data.describe()

        Retribucion       Area      Nivel
count     31.000000  31.000000  31.000000
mean   28400.000000   3.387097   1.225806
std    11817.501146   0.495138   0.560338
min    18000.000000   3.000000   1.000000
25%    18500.000000   3.000000   1.000000
50%    23000.000000   3.000000   1.000000
75%    34000.000000   4.000000   1.000000
max    56000.000000   4.000000   3.000000

# Automatización

In [81]:
raw_data['Area'].unique()

array([3, 4])

In [82]:
contrataciones_avg = []
for area in sorted(raw_data['Area'].unique()):
    for grupo in sorted(raw_data[raw_data['Area']==area]['Grupo'].unique()):
        for nivel in sorted(raw_data[(raw_data['Area']==area) & (raw_data['Grupo']==grupo)]['Nivel'].unique()):
            area_grupo_nivel_sueldos=raw_data[(raw_data['Area']==area) & (raw_data['Grupo']==grupo) & (raw_data['Nivel']==nivel)]['Retribucion']
            print(f'{area},{grupo},{nivel}: {area_grupo_nivel_sueldos.count()} -> {round(area_grupo_nivel_sueldos.mean())}')
            fila = [area,grupo,nivel,area_grupo_nivel_sueldos.count(),round(area_grupo_nivel_sueldos.mean())]
            contrataciones_avg.append(fila)

3,A,1: 1 -> 56000
3,B,1: 2 -> 46200
3,C,2: 1 -> 28000
3,D,1: 4 -> 24750
3,D,2: 1 -> 27000
3,D,3: 1 -> 24000
3,E,1: 8 -> 18500
3,E,2: 1 -> 18000
4,A,1: 1 -> 50000
4,B,1: 2 -> 49000
4,C,1: 3 -> 34000
4,C,3: 1 -> 23000
4,D,1: 5 -> 23000

In [83]:
contrataciones_avg

[[np.int64(3), 'A', np.int64(1), np.int64(1), 56000],
 [np.int64(3), 'B', np.int64(1), np.int64(2), 46200],
 [np.int64(3), 'C', np.int64(2), np.int64(1), 28000],
 [np.int64(3), 'D', np.int64(1), np.int64(4), 24750],
 [np.int64(3), 'D', np.int64(2), np.int64(1), 27000],
 [np.int64(3), 'D', np.int64(3), np.int64(1), 24000],
 [np.int64(3), 'E', np.int64(1), np.int64(8), 18500],
 [np.int64(3), 'E', np.int64(2), np.int64(1), 18000],
 [np.int64(4), 'A', np.int64(1), np.int64(1), 50000],
 [np.int64(4), 'B', np.int64(1), np.int64(2), 49000],
 [np.int64(4), 'C', np.int64(1), np.int64(3), 34000],
 [np.int64(4), 'C', np.int64(3), np.int64(1), 23000],
 [np.int64(4), 'D', np.int64(1), np.int64(5), 23000]]

In [84]:
calor = pd.DataFrame(contrataciones_avg)

In [85]:
calor.columns.values

array([0, 1, 2, 3, 4])

In [86]:
columns = ['Area','Grupo','Nivel','Contrataciones','Salario Medio']
calor.columns = columns

In [87]:
calor.head(20)

    Area Grupo  Nivel  Contrataciones  Salario Medio
0      3     A      1               1          56000
1      3     B      1               2          46200
2      3     C      2               1          28000
3      3     D      1               4          24750
4      3     D      2               1          27000
5      3     D      3               1          24000
6      3     E      1               8          18500
7      3     E      2               1          18000
8      4     A      1               1          50000
9      4     B      1               2          49000
10     4     C      1               3          34000
11     4     C      3               1          23000
12     4     D      1               5          23000

In [88]:
calor.to_csv(dirpath + 'MediaContrataciones.csv', index = False)