In [51]:
import pandas as pd
import numpy

In [52]:
dirpath = 'C:/Users/mvgarcia/Downloads/ComiteEmpresa/cb/2021/'
raw_data = pd.read_csv(dirpath + 'Preprocessed.csv')

In [53]:
raw_data.head()

              Id       Fecha  Retribucion  Area Grupo Nivel
0  18.10.2021000  18.10.2021    2300000.0     3     C   III
1  10.11.2021001  10.11.2021    2200000.0     3     C   III
2  12.12.2021002  12.12.2021    2200000.0     3     C   III
3  12.10.2021003  12.10.2021    2200000.0     3     C   III
4  15.10.2021004  15.10.2021    2000000.0     3     D     I

In [54]:
raw_data.describe()

        Retribucion       Area
count  9.400000e+01  94.000000
mean   2.498617e+06   2.893617
std    9.028966e+05   0.309980
min    2.700000e+04   2.000000
25%    2.012500e+06   3.000000
50%    2.200000e+06   3.000000
75%    2.737500e+06   3.000000
max    5.700000e+06   3.000000

# Automatización

In [55]:
raw_data['Area'].unique()

array([3, 2])

In [56]:
contrataciones_avg = []
for area in sorted(raw_data['Area'].unique()):
    for grupo in sorted(raw_data[raw_data['Area']==area]['Grupo'].unique()):
        for nivel in sorted(raw_data[(raw_data['Area']==area) & (raw_data['Grupo']==grupo)]['Nivel'].unique()):
            area_grupo_nivel_sueldos=raw_data[(raw_data['Area']==area) & (raw_data['Grupo']==grupo) & (raw_data['Nivel']==nivel)]['Retribucion']
            print(f'{area},{grupo},{nivel}: {area_grupo_nivel_sueldos.count()} -> {round(area_grupo_nivel_sueldos.mean())}')
            fila = [area,grupo,nivel,area_grupo_nivel_sueldos.count(),round(area_grupo_nivel_sueldos.mean())]
            contrataciones_avg.append(fila)

2,C,III: 1 -> 3250000
2,D,III: 5 -> 2280200
2,E,II: 4 -> 1696250
3,A,I: 1 -> 5700000
3,B,I: 8 -> 3879750
3,C,I: 14 -> 2922929
3,C,II: 1 -> 3500000
3,C,III: 27 -> 2262963
3,D,I: 22 -> 2309091
3,D,III: 3 -> 1766667
3,E,I: 7 -> 1896429
3,E,II: 1 -> 1800000

In [57]:
contrataciones_avg

[[np.int64(2), 'C', 'III', np.int64(1), 3250000],
 [np.int64(2), 'D', 'III', np.int64(5), 2280200],
 [np.int64(2), 'E', 'II', np.int64(4), 1696250],
 [np.int64(3), 'A', 'I', np.int64(1), 5700000],
 [np.int64(3), 'B', 'I', np.int64(8), 3879750],
 [np.int64(3), 'C', 'I', np.int64(14), 2922929],
 [np.int64(3), 'C', 'II', np.int64(1), 3500000],
 [np.int64(3), 'C', 'III', np.int64(27), 2262963],
 [np.int64(3), 'D', 'I', np.int64(22), 2309091],
 [np.int64(3), 'D', 'III', np.int64(3), 1766667],
 [np.int64(3), 'E', 'I', np.int64(7), 1896429],
 [np.int64(3), 'E', 'II', np.int64(1), 1800000]]

In [58]:
calor = pd.DataFrame(contrataciones_avg)

In [59]:
calor.columns.values

array([0, 1, 2, 3, 4])

In [60]:
columns = ['Area','Grupo','Nivel','Contrataciones','Salario Medio']
calor.columns = columns

In [61]:
calor.head(20)

    Area Grupo Nivel  Contrataciones  Salario Medio
0      2     C   III               1        3250000
1      2     D   III               5        2280200
2      2     E    II               4        1696250
3      3     A     I               1        5700000
4      3     B     I               8        3879750
5      3     C     I              14        2922929
6      3     C    II               1        3500000
7      3     C   III              27        2262963
8      3     D     I              22        2309091
9      3     D   III               3        1766667
10     3     E     I               7        1896429
11     3     E    II               1        1800000

In [62]:
calor.to_csv(dirpath + 'MediaContrataciones.csv', index = False)