Instrucciones

In [132]:
import pandas as pd

In [133]:
dirpath='C:/Users/mvgarcia/Downloads/ComiteEmpresa/cb/2021/'
raw_data = pd.read_csv(dirpath + 'Registro_raw.csv')
raw_data

,DNI,Fecha,Retribucion,Categoria,Sociedad,Nombre
0,NaN,18.10.2021,23000.00,Area 3 Grupo C Nivel III,INDRA SOLUCIONES TI,Adrián Doval García
1,NaN,10.11.2021,22000.00,Area 3 Grupo C Nivel III,INDRA SOLUCIONES TI,Alba Martínez Rodríguez
2,NaN,12.12.2021,22000.00,Area 3 Grupo C Nivel III,INDRA SOLUCIONES TI,Alberto Amoedo Domínguez
3,NaN,12.10.2021,22000.00,Area 3 Grupo C Nivel III,INDRA SOLUCIONES TI,Alberto Amoedo Domínguez
4,NaN,15.10.2021,20000.00,Area 3 Grupo D Nivel I,INDRA SOLUCIONES TI,ALBERTO GABRIEL YAÑEZ NUÑEZ
...,...,...,...,...,...,...
89,NaN,20.09.2021,48400.00,Area 3 Grupo B Nivel I,INDRA SOLUCIONES TI,RUBEN RODRIGUEZ GOMEZ
90,NaN,14.06.2021,25440.00,Area 3 Grupo C Nivel I,INDRA SOLUCIONES TI,Rubén Suárez Lareo
91,NaN,01.03.2021,28000.00,Area 3 Grupo D Nivel I,INDRA SOLUCIONES TI,SIMON ALONSO SANCHEZ
92,NaN,01.07.2021,22000.00,Area 3 Grupo C Nivel III,INDRA SOLUCIONES TI,Iago Ubeira Martínez
93,NaN,20.09.2021,50000.00,Area 3 Grupo B Nivel I,INDRA SOLUCIONES TI,Willie José Betancourt Simoza

In [134]:
def limpia_sueldo(x):
    if pd.api.types.is_number(x):
        return x
    else:
        return x.replace('.', '').replace(',', '.')

In [135]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 94 entries, 0 to 93
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   DNI          0 non-null      float64
 1   Fecha        94 non-null     object
 2   Retribucion  94 non-null     object
 3   Categoria    94 non-null     object
 4   Sociedad     94 non-null     object
 5   Nombre       94 non-null     object
dtypes: float64(1), object(5)
memory usage: 4.5+ KB

In [136]:
data = raw_data.copy()

In [137]:
data['Id']=[(data['Fecha'][i]+f'{i:03d}') for i in range(0, len(data))]

In [138]:
data['Retribucion']=raw_data['Retribucion'].apply(limpia_sueldo).astype('float')

In [139]:
data

,DNI,Fecha,Retribucion,Categoria,Sociedad,Nombre,Id
0,NaN,18.10.2021,2300000.0,Area 3 Grupo C Nivel III,INDRA SOLUCIONES TI,Adrián Doval García,18.10.2021000
1,NaN,10.11.2021,2200000.0,Area 3 Grupo C Nivel III,INDRA SOLUCIONES TI,Alba Martínez Rodríguez,10.11.2021001
2,NaN,12.12.2021,2200000.0,Area 3 Grupo C Nivel III,INDRA SOLUCIONES TI,Alberto Amoedo Domínguez,12.12.2021002
3,NaN,12.10.2021,2200000.0,Area 3 Grupo C Nivel III,INDRA SOLUCIONES TI,Alberto Amoedo Domínguez,12.10.2021003
4,NaN,15.10.2021,2000000.0,Area 3 Grupo D Nivel I,INDRA SOLUCIONES TI,ALBERTO GABRIEL YAÑEZ NUÑEZ,15.10.2021004
...,...,...,...,...,...,...,...
89,NaN,20.09.2021,4840000.0,Area 3 Grupo B Nivel I,INDRA SOLUCIONES TI,RUBEN RODRIGUEZ GOMEZ,20.09.2021089
90,NaN,14.06.2021,2544000.0,Area 3 Grupo C Nivel I,INDRA SOLUCIONES TI,Rubén Suárez Lareo,14.06.2021090
91,NaN,01.03.2021,2800000.0,Area 3 Grupo D Nivel I,INDRA SOLUCIONES TI,SIMON ALONSO SANCHEZ,01.03.2021091
92,NaN,01.07.2021,2200000.0,Area 3 Grupo C Nivel III,INDRA SOLUCIONES TI,Iago Ubeira Martínez,01.07.2021092
93,NaN,20.09.2021,5000000.0,Area 3 Grupo B Nivel I,INDRA SOLUCIONES TI,Willie José Betancourt Simoza,20.09.2021093

In [140]:
data['Area']=[i.split()[1] for i in data['Categoria']]
data['Grupo']=[i.split()[3] for i in data['Categoria']]
data['Nivel']=[i.split()[5] for i in data['Categoria']]

In [141]:
data

,DNI,Fecha,Retribucion,Categoria,Sociedad,Nombre,Id,Area,Grupo,Nivel
0,NaN,18.10.2021,2300000.0,Area 3 Grupo C Nivel III,INDRA SOLUCIONES TI,Adrián Doval García,18.10.2021000,3,C,III
1,NaN,10.11.2021,2200000.0,Area 3 Grupo C Nivel III,INDRA SOLUCIONES TI,Alba Martínez Rodríguez,10.11.2021001,3,C,III
2,NaN,12.12.2021,2200000.0,Area 3 Grupo C Nivel III,INDRA SOLUCIONES TI,Alberto Amoedo Domínguez,12.12.2021002,3,C,III
3,NaN,12.10.2021,2200000.0,Area 3 Grupo C Nivel III,INDRA SOLUCIONES TI,Alberto Amoedo Domínguez,12.10.2021003,3,C,III
4,NaN,15.10.2021,2000000.0,Area 3 Grupo D Nivel I,INDRA SOLUCIONES TI,ALBERTO GABRIEL YAÑEZ NUÑEZ,15.10.2021004,3,D,I
...,...,...,...,...,...,...,...,...,...,...
89,NaN,20.09.2021,4840000.0,Area 3 Grupo B Nivel I,INDRA SOLUCIONES TI,RUBEN RODRIGUEZ GOMEZ,20.09.2021089,3,B,I
90,NaN,14.06.2021,2544000.0,Area 3 Grupo C Nivel I,INDRA SOLUCIONES TI,Rubén Suárez Lareo,14.06.2021090,3,C,I
91,NaN,01.03.2021,2800000.0,Area 3 Grupo D Nivel I,INDRA SOLUCIONES TI,SIMON ALONSO SANCHEZ,01.03.2021091,3,D,I
92,NaN,01.07.2021,2200000.0,Area 3 Grupo C Nivel III,INDRA SOLUCIONES TI,Iago Ubeira Martínez,01.07.2021092,3,C,III
93,NaN,20.09.2021,5000000.0,Area 3 Grupo B Nivel I,INDRA SOLUCIONES TI,Willie José Betancourt Simoza,20.09.2021093,3,B,I

In [142]:
data.columns.values

array(['DNI', 'Fecha', 'Retribucion', 'Categoria', 'Sociedad', 'Nombre',
       'Id', 'Area', 'Grupo', 'Nivel'], dtype=object)

In [143]:
preprocessed=data[['Id', 'Fecha', 'Retribucion', 'Area', 'Grupo', 'Nivel']]

In [144]:
preprocessed

               Id       Fecha  Retribucion Area Grupo Nivel
0   18.10.2021000  18.10.2021    2300000.0    3     C   III
1   10.11.2021001  10.11.2021    2200000.0    3     C   III
2   12.12.2021002  12.12.2021    2200000.0    3     C   III
3   12.10.2021003  12.10.2021    2200000.0    3     C   III
4   15.10.2021004  15.10.2021    2000000.0    3     D     I
..            ...         ...          ...  ...   ...   ...
89  20.09.2021089  20.09.2021    4840000.0    3     B     I
90  14.06.2021090  14.06.2021    2544000.0    3     C     I
91  01.03.2021091  01.03.2021    2800000.0    3     D     I
92  01.07.2021092  01.07.2021    2200000.0    3     C   III
93  20.09.2021093  20.09.2021    5000000.0    3     B     I

[94 rows x 6 columns]

In [145]:
preprocessed.to_csv(dirpath + 'Preprocessed.csv', index = False)

In [146]:
xref=data[['Nombre','Id']]

In [147]:
xref.to_csv(dirpath + 'XRef.csv',index = False)