Instrucciones

In [99]:
import pandas as pd

In [100]:
dirpath='C:/Users/mvgarcia/Downloads/ComiteEmpresa/cb/2024/'
raw_data = pd.read_csv(dirpath + 'Registro_raw.csv')
raw_data

,DNI,Fecha,Retribucion,Categoria,Sociedad,Nombre
0,NaN,07.10.2024,"18.500,00",Area 3 Grupo E Nivel 1,INDRA SOLUCIONES TI,Aarón Castro Vila
1,NaN,14.02.2024,"18.500,00",Area 3 Grupo E Nivel 1,INDRA SOLUCIONES TI,ALEJANDRO ESTRAMIL REYES
2,NaN,16.09.2024,"23.000,00",Area 4 Grupo D Nivel 1,INDRA SOLUCIONES TI,Andrea Alvite López
3,NaN,24.06.2024,"18.000,00",Area 3 Grupo E Nivel 2,INDRA SOLUCIONES TI,Andrés Soto López
4,NaN,04.11.2024,"22.000,00",Area 3 Grupo D Nivel 1,INDRA SOLUCIONES TI,Anxo Alvite González
5,NaN,04.03.2024,"18.500,00",Area 3 Grupo E Nivel 1,INDRA SOLUCIONES TI,BRUNO LOPEZ BARCIA
6,NaN,18.03.2024,"30.000,00",Area 4 Grupo C Nivel 1,INDRA SOLUCIONES TI,Carolina Martín García
7,NaN,14.10.2024,"23.000,00",Area 4 Grupo D Nivel 1,INDRA SOLUCIONES TI,Cristina Gómez Núñez
8,NaN,16.09.2024,"50.000,00",Area 4 Grupo A Nivel 1,INDRA SOLUCIONES TI,David López Martín
9,NaN,02.12.2024,"18.500,00",Area 3 Grupo E Nivel 1,INDRA SOLUCIONES TI,David Vidal Suaréz
10,NaN,18.11.2024,"22.000,00",Area 3 Grupo D Nivel 1,INDRA SOLUCIONES TI,Diego Vázquez Pedreira
11,NaN,26.02.2024,"41.000,00",Area 3 Grupo B Nivel 1,INDRA SOLUCIONES TI,Eladio Orín Ceballos
12,NaN,04.09.2024,"23.000,00",Area 4 Grupo D Nivel 1,INDRA SOLUCIONES TI,Enrique Prado Allegue
13,NaN,22.07.2024,"27.000,00",Area 3 Grupo D Nivel 2,INDRA SOLUCIONES TI,Isabel Martínez Romero Malfaz
14,NaN,25.11.2024,"33.000,00",Area 3 Grupo D Nivel 1,INDRA SOLUCIONES TI,Jacobo Bahamonde Rey
15,NaN,18.11.2024,"22.000,00",Area 3 Grupo D Nivel 1,INDRA SOLUCIONES TI,Jorge Fernández Matos
16,NaN,07.05.2024,"23.000,00",Area 4 Grupo D Nivel 1,INDRA SOLUCIONES TI,Leonardo Leiro Vidal
17,NaN,25.06.2024,"56.000,00",Area 3 Grupo A Nivel 1,INDRA SOLUCIONES TI,Maira Alejandra Carvajal Chaparro
18,NaN,01.04.2024,"35.000,00",Area 4 Grupo C Nivel 1,INDRA SOLUCIONES TI,María de la O Dieguez Alejos
19,NaN,28.02.2024,"37.000,00",Area 4 Grupo C Nivel 1,INDRA SOLUCIONES TI,María Fernanda Jover Martínez
20,NaN,02.05.2024,"18.500,00",Area 3 Grupo E Nivel 1,INDRA SOLUCIONES TI,Martín Mouzo Silva
21,NaN,29.02.2024,"23.000,00",Area 4 Grupo C Nivel 3,INDRA SOLUCIONES TI,Martín Torres López
22,NaN,25.03.2024,"24.000,00",Area 3 Grupo D Nivel 3,INDRA SOLUCIONES TI,Mary Alejandra Sánchez Gabarre
23,NaN,14.11.2024,"23.000,00",Area 4 Grupo D Nivel 1,INDRA SOLUCIONES TI,Miguel Legazpi Aller
24,NaN,01.04.2024,"55.000,00",Area 4 Grupo B Nivel 1,INDRA SOLUCIONES TI,Pedro López Roig
25,NaN,26.11.2024,"43.000,00",Area 4 Grupo B Nivel 1,INDRA SOLUCIONES TI,Rafael Eduardo Jiménez Febres
26,NaN,02.01.2024,"28.000,00",Area 3 Grupo C Nivel 2,INDRA SOLUCIONES TI,Raúl Nieto Ameneiros
27,NaN,21.10.2024,"51.400,00",Area 3 Grupo B Nivel 1,INDRA SOLUCIONES TI,ROBERTO PEDREIRA ULLOA
28,NaN,24.09.2024,"18.500,00",Area 3 Grupo E Nivel 1,INDRA SOLUCIONES TI,Rubén Martínez Santos
29,NaN,28.10.2024,"18.500,00",Area 3 Grupo E Nivel 1,INDRA SOLUCIONES TI,Steven González Rodríguez
30,NaN,25.01.2024,"18.500,00",Area 3 Grupo E Nivel 1,INDRA SOLUCIONES TI,Xavier Mariño Porteiro

In [101]:
def limpia_sueldo(x):
    return x.replace('.', '').replace(',', '.')

In [102]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   DNI          0 non-null      float64
 1   Fecha        31 non-null     object
 2   Retribucion  31 non-null     object
 3   Categoria    31 non-null     object
 4   Sociedad     31 non-null     object
 5   Nombre       31 non-null     object
dtypes: float64(1), object(5)
memory usage: 1.6+ KB

In [103]:
data = raw_data.copy()

In [104]:
data['Id']=[(data['Fecha'][i]+f'{i:03d}') for i in range(0, len(data))]

In [105]:
data['Retribucion']=raw_data['Retribucion'].apply(limpia_sueldo).astype('float')

In [106]:
data

,DNI,Fecha,Retribucion,Categoria,Sociedad,Nombre,Id
0,NaN,07.10.2024,18500.0,Area 3 Grupo E Nivel 1,INDRA SOLUCIONES TI,Aarón Castro Vila,07.10.2024000
1,NaN,14.02.2024,18500.0,Area 3 Grupo E Nivel 1,INDRA SOLUCIONES TI,ALEJANDRO ESTRAMIL REYES,14.02.2024001
2,NaN,16.09.2024,23000.0,Area 4 Grupo D Nivel 1,INDRA SOLUCIONES TI,Andrea Alvite López,16.09.2024002
3,NaN,24.06.2024,18000.0,Area 3 Grupo E Nivel 2,INDRA SOLUCIONES TI,Andrés Soto López,24.06.2024003
4,NaN,04.11.2024,22000.0,Area 3 Grupo D Nivel 1,INDRA SOLUCIONES TI,Anxo Alvite González,04.11.2024004
5,NaN,04.03.2024,18500.0,Area 3 Grupo E Nivel 1,INDRA SOLUCIONES TI,BRUNO LOPEZ BARCIA,04.03.2024005
6,NaN,18.03.2024,30000.0,Area 4 Grupo C Nivel 1,INDRA SOLUCIONES TI,Carolina Martín García,18.03.2024006
7,NaN,14.10.2024,23000.0,Area 4 Grupo D Nivel 1,INDRA SOLUCIONES TI,Cristina Gómez Núñez,14.10.2024007
8,NaN,16.09.2024,50000.0,Area 4 Grupo A Nivel 1,INDRA SOLUCIONES TI,David López Martín,16.09.2024008
9,NaN,02.12.2024,18500.0,Area 3 Grupo E Nivel 1,INDRA SOLUCIONES TI,David Vidal Suaréz,02.12.2024009
10,NaN,18.11.2024,22000.0,Area 3 Grupo D Nivel 1,INDRA SOLUCIONES TI,Diego Vázquez Pedreira,18.11.2024010
11,NaN,26.02.2024,41000.0,Area 3 Grupo B Nivel 1,INDRA SOLUCIONES TI,Eladio Orín Ceballos,26.02.2024011
12,NaN,04.09.2024,23000.0,Area 4 Grupo D Nivel 1,INDRA SOLUCIONES TI,Enrique Prado Allegue,04.09.2024012
13,NaN,22.07.2024,27000.0,Area 3 Grupo D Nivel 2,INDRA SOLUCIONES TI,Isabel Martínez Romero Malfaz,22.07.2024013
14,NaN,25.11.2024,33000.0,Area 3 Grupo D Nivel 1,INDRA SOLUCIONES TI,Jacobo Bahamonde Rey,25.11.2024014
15,NaN,18.11.2024,22000.0,Area 3 Grupo D Nivel 1,INDRA SOLUCIONES TI,Jorge Fernández Matos,18.11.2024015
16,NaN,07.05.2024,23000.0,Area 4 Grupo D Nivel 1,INDRA SOLUCIONES TI,Leonardo Leiro Vidal,07.05.2024016
17,NaN,25.06.2024,56000.0,Area 3 Grupo A Nivel 1,INDRA SOLUCIONES TI,Maira Alejandra Carvajal Chaparro,25.06.2024017
18,NaN,01.04.2024,35000.0,Area 4 Grupo C Nivel 1,INDRA SOLUCIONES TI,María de la O Dieguez Alejos,01.04.2024018
19,NaN,28.02.2024,37000.0,Area 4 Grupo C Nivel 1,INDRA SOLUCIONES TI,María Fernanda Jover Martínez,28.02.2024019
20,NaN,02.05.2024,18500.0,Area 3 Grupo E Nivel 1,INDRA SOLUCIONES TI,Martín Mouzo Silva,02.05.2024020
21,NaN,29.02.2024,23000.0,Area 4 Grupo C Nivel 3,INDRA SOLUCIONES TI,Martín Torres López,29.02.2024021
22,NaN,25.03.2024,24000.0,Area 3 Grupo D Nivel 3,INDRA SOLUCIONES TI,Mary Alejandra Sánchez Gabarre,25.03.2024022
23,NaN,14.11.2024,23000.0,Area 4 Grupo D Nivel 1,INDRA SOLUCIONES TI,Miguel Legazpi Aller,14.11.2024023
24,NaN,01.04.2024,55000.0,Area 4 Grupo B Nivel 1,INDRA SOLUCIONES TI,Pedro López Roig,01.04.2024024
25,NaN,26.11.2024,43000.0,Area 4 Grupo B Nivel 1,INDRA SOLUCIONES TI,Rafael Eduardo Jiménez Febres,26.11.2024025
26,NaN,02.01.2024,28000.0,Area 3 Grupo C Nivel 2,INDRA SOLUCIONES TI,Raúl Nieto Ameneiros,02.01.2024026
27,NaN,21.10.2024,51400.0,Area 3 Grupo B Nivel 1,INDRA SOLUCIONES TI,ROBERTO PEDREIRA ULLOA,21.10.2024027
28,NaN,24.09.2024,18500.0,Area 3 Grupo E Nivel 1,INDRA SOLUCIONES TI,Rubén Martínez Santos,24.09.2024028
29,NaN,28.10.2024,18500.0,Area 3 Grupo E Nivel 1,INDRA SOLUCIONES TI,Steven González Rodríguez,28.10.2024029
30,NaN,25.01.2024,18500.0,Area 3 Grupo E Nivel 1,INDRA SOLUCIONES TI,Xavier Mariño Porteiro,25.01.2024030

In [107]:
data['Area']=[i.split()[1] for i in data['Categoria']]
data['Grupo']=[i.split()[3] for i in data['Categoria']]
data['Nivel']=[i.split()[5] for i in data['Categoria']]

In [108]:
data

,DNI,Fecha,Retribucion,Categoria,Sociedad,Nombre,Id,Area,Grupo,Nivel
0,NaN,07.10.2024,18500.0,Area 3 Grupo E Nivel 1,INDRA SOLUCIONES TI,Aarón Castro Vila,07.10.2024000,3,E,1
1,NaN,14.02.2024,18500.0,Area 3 Grupo E Nivel 1,INDRA SOLUCIONES TI,ALEJANDRO ESTRAMIL REYES,14.02.2024001,3,E,1
2,NaN,16.09.2024,23000.0,Area 4 Grupo D Nivel 1,INDRA SOLUCIONES TI,Andrea Alvite López,16.09.2024002,4,D,1
3,NaN,24.06.2024,18000.0,Area 3 Grupo E Nivel 2,INDRA SOLUCIONES TI,Andrés Soto López,24.06.2024003,3,E,2
4,NaN,04.11.2024,22000.0,Area 3 Grupo D Nivel 1,INDRA SOLUCIONES TI,Anxo Alvite González,04.11.2024004,3,D,1
5,NaN,04.03.2024,18500.0,Area 3 Grupo E Nivel 1,INDRA SOLUCIONES TI,BRUNO LOPEZ BARCIA,04.03.2024005,3,E,1
6,NaN,18.03.2024,30000.0,Area 4 Grupo C Nivel 1,INDRA SOLUCIONES TI,Carolina Martín García,18.03.2024006,4,C,1
7,NaN,14.10.2024,23000.0,Area 4 Grupo D Nivel 1,INDRA SOLUCIONES TI,Cristina Gómez Núñez,14.10.2024007,4,D,1
8,NaN,16.09.2024,50000.0,Area 4 Grupo A Nivel 1,INDRA SOLUCIONES TI,David López Martín,16.09.2024008,4,A,1
9,NaN,02.12.2024,18500.0,Area 3 Grupo E Nivel 1,INDRA SOLUCIONES TI,David Vidal Suaréz,02.12.2024009,3,E,1
10,NaN,18.11.2024,22000.0,Area 3 Grupo D Nivel 1,INDRA SOLUCIONES TI,Diego Vázquez Pedreira,18.11.2024010,3,D,1
11,NaN,26.02.2024,41000.0,Area 3 Grupo B Nivel 1,INDRA SOLUCIONES TI,Eladio Orín Ceballos,26.02.2024011,3,B,1
12,NaN,04.09.2024,23000.0,Area 4 Grupo D Nivel 1,INDRA SOLUCIONES TI,Enrique Prado Allegue,04.09.2024012,4,D,1
13,NaN,22.07.2024,27000.0,Area 3 Grupo D Nivel 2,INDRA SOLUCIONES TI,Isabel Martínez Romero Malfaz,22.07.2024013,3,D,2
14,NaN,25.11.2024,33000.0,Area 3 Grupo D Nivel 1,INDRA SOLUCIONES TI,Jacobo Bahamonde Rey,25.11.2024014,3,D,1
15,NaN,18.11.2024,22000.0,Area 3 Grupo D Nivel 1,INDRA SOLUCIONES TI,Jorge Fernández Matos,18.11.2024015,3,D,1
16,NaN,07.05.2024,23000.0,Area 4 Grupo D Nivel 1,INDRA SOLUCIONES TI,Leonardo Leiro Vidal,07.05.2024016,4,D,1
17,NaN,25.06.2024,56000.0,Area 3 Grupo A Nivel 1,INDRA SOLUCIONES TI,Maira Alejandra Carvajal Chaparro,25.06.2024017,3,A,1
18,NaN,01.04.2024,35000.0,Area 4 Grupo C Nivel 1,INDRA SOLUCIONES TI,María de la O Dieguez Alejos,01.04.2024018,4,C,1
19,NaN,28.02.2024,37000.0,Area 4 Grupo C Nivel 1,INDRA SOLUCIONES TI,María Fernanda Jover Martínez,28.02.2024019,4,C,1
20,NaN,02.05.2024,18500.0,Area 3 Grupo E Nivel 1,INDRA SOLUCIONES TI,Martín Mouzo Silva,02.05.2024020,3,E,1
21,NaN,29.02.2024,23000.0,Area 4 Grupo C Nivel 3,INDRA SOLUCIONES TI,Martín Torres López,29.02.2024021,4,C,3
22,NaN,25.03.2024,24000.0,Area 3 Grupo D Nivel 3,INDRA SOLUCIONES TI,Mary Alejandra Sánchez Gabarre,25.03.2024022,3,D,3
23,NaN,14.11.2024,23000.0,Area 4 Grupo D Nivel 1,INDRA SOLUCIONES TI,Miguel Legazpi Aller,14.11.2024023,4,D,1
24,NaN,01.04.2024,55000.0,Area 4 Grupo B Nivel 1,INDRA SOLUCIONES TI,Pedro López Roig,01.04.2024024,4,B,1
25,NaN,26.11.2024,43000.0,Area 4 Grupo B Nivel 1,INDRA SOLUCIONES TI,Rafael Eduardo Jiménez Febres,26.11.2024025,4,B,1
26,NaN,02.01.2024,28000.0,Area 3 Grupo C Nivel 2,INDRA SOLUCIONES TI,Raúl Nieto Ameneiros,02.01.2024026,3,C,2
27,NaN,21.10.2024,51400.0,Area 3 Grupo B Nivel 1,INDRA SOLUCIONES TI,ROBERTO PEDREIRA ULLOA,21.10.2024027,3,B,1
28,NaN,24.09.2024,18500.0,Area 3 Grupo E Nivel 1,INDRA SOLUCIONES TI,Rubén Martínez Santos,24.09.2024028,3,E,1
29,NaN,28.10.2024,18500.0,Area 3 Grupo E Nivel 1,INDRA SOLUCIONES TI,Steven González Rodríguez,28.10.2024029,3,E,1
30,NaN,25.01.2024,18500.0,Area 3 Grupo E Nivel 1,INDRA SOLUCIONES TI,Xavier Mariño Porteiro,25.01.2024030,3,E,1

In [109]:
data.columns.values

array(['DNI', 'Fecha', 'Retribucion', 'Categoria', 'Sociedad', 'Nombre',
       'Id', 'Area', 'Grupo', 'Nivel'], dtype=object)

In [110]:
preprocessed=data[['Id', 'Fecha', 'Retribucion', 'Area', 'Grupo', 'Nivel']]

In [111]:
preprocessed

               Id       Fecha  Retribucion Area Grupo Nivel
0   07.10.2024000  07.10.2024      18500.0    3     E     1
1   14.02.2024001  14.02.2024      18500.0    3     E     1
2   16.09.2024002  16.09.2024      23000.0    4     D     1
3   24.06.2024003  24.06.2024      18000.0    3     E     2
4   04.11.2024004  04.11.2024      22000.0    3     D     1
5   04.03.2024005  04.03.2024      18500.0    3     E     1
6   18.03.2024006  18.03.2024      30000.0    4     C     1
7   14.10.2024007  14.10.2024      23000.0    4     D     1
8   16.09.2024008  16.09.2024      50000.0    4     A     1
9   02.12.2024009  02.12.2024      18500.0    3     E     1
10  18.11.2024010  18.11.2024      22000.0    3     D     1
11  26.02.2024011  26.02.2024      41000.0    3     B     1
12  04.09.2024012  04.09.2024      23000.0    4     D     1
13  22.07.2024013  22.07.2024      27000.0    3     D     2
14  25.11.2024014  25.11.2024      33000.0    3     D     1
15  18.11.2024015  18.11.2024      22000.0    3     D     1
16  07.05.2024016  07.05.2024      23000.0    4     D     1
17  25.06.2024017  25.06.2024      56000.0    3     A     1
18  01.04.2024018  01.04.2024      35000.0    4     C     1
19  28.02.2024019  28.02.2024      37000.0    4     C     1
20  02.05.2024020  02.05.2024      18500.0    3     E     1
21  29.02.2024021  29.02.2024      23000.0    4     C     3
22  25.03.2024022  25.03.2024      24000.0    3     D     3
23  14.11.2024023  14.11.2024      23000.0    4     D     1
24  01.04.2024024  01.04.2024      55000.0    4     B     1
25  26.11.2024025  26.11.2024      43000.0    4     B     1
26  02.01.2024026  02.01.2024      28000.0    3     C     2
27  21.10.2024027  21.10.2024      51400.0    3     B     1
28  24.09.2024028  24.09.2024      18500.0    3     E     1
29  28.10.2024029  28.10.2024      18500.0    3     E     1
30  25.01.2024030  25.01.2024      18500.0    3     E     1

In [112]:
preprocessed.to_csv(dirpath + 'Preprocessed.csv', index = False)

In [118]:
xref=data[['Nombre','Id']]

In [119]:
xref.to_csv(dirpath + 'XRef.csv',index = False)